### ISSUE TITLE
Second Screen

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#10]
_From @tidoust on October 12, 2016 6:57_

https://www.w3.org/2002/09/wbs/33280/sswg-charter-2016/results

_Copied from original issue: tidoust/strategy#4_

**Comment by svgeesus** [comment]
Ongoing AC review, ends 25 October.

**Comment by wseltzer** [comment]
Just over the line :+1:

**Comment by plehegar** [comment]
Francois asked project to help and I obliged since it was easy:
 https://lists.w3.org/Archives/Team/team-project/2016Oct/0004.html
we're short of 1 but think we could move forward as-is.
waiting on Francois for a draft of director decision.
let me know if you prefer that I yield to strategy for this one.

**Comment by tidoust** [comment]
Comment from @plehegar suggests that I may not have contacted the right person :)
I assumed that Project management was in charge of charter renewals when scope does not change. Is that not the case?

**Comment by plehegar** [comment]
actually, if the scope didn't change, you did the right thing. So, I'm not helping Strategy and I'm doing what I'm supposed to do :)

**Comment by wseltzer** [comment]
sounds good to me!
