### ISSUE TITLE
Chinese Web Interest Group charter 2020

### ISSUE THREAD

**Issue by xfq** [w3c/strategy#224]
New charter proposal, reviewers please take note.

# Charter Review

[Chinese Web Interest Group Draft Charter](https://w3c.github.io/chinese-ig-charter/charter-2020.html)

 - [x] Existing IG recharter
 - [Diff from previous charter](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2018%2F09%2Fchinese-web-ig-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fchinese-ig-charter%2Fcharter-2020.html)

Horizontal Reviews (intended to be checked only by horizontal reviewers when they are satisfied with the charter)
  - [ ] Accessibility (a11y)
  - [ ] Internationalization (i18n)
  - [ ] Privacy
  - [ ] Security

Communities suggested for outreach: 

Known or potential areas of concern?: 

Where would charter proponents like to see issues raised? [GitHub](https://github.com/w3c/chinese-ig-charter/issues)

Anything else we should think about as we review?

**Comment by michael-n-cooper** [comment]
No comments from APA. Over to @brewerj to complete accessibility horizontal review.

**Comment by himorin** [comment]
No request from i18n WG. We'd appreciate that this charter mentions on Chinese Layout Task Force as collaboration.

**Comment by brewerj** [comment]
Hi Fuqiao, given that the proposed group is an Interest Group without Rec-track deliverables, but with the potential to incubate good ideas rapidly, I suggest adding to the [Coordination section](https://w3c.github.io/chinese-ig-charter/charter-2020.html#coordination): 
"Discuss potential accessibility issues and opportunities with the [Accessible Platform Architectures (APA) Working Group](https://www.w3.org/WAI/APA/), including early orientation to the [Framework for Accessible Specification of Technology](https://w3c.github.io/apa/fast/) for ideas emerging from this Interest Group."
Noting that the draft charter is otherwise ready to move through W3M review for AC review, I make this as a suggestion only. Please let me know if you have any questions. Thanks.

**Comment by xfq** [comment]
Thanks @brewerj. I've added APA and FAST into the charter.

**Comment by samuelweiler** [comment]
I filed two issues for discussion, one about security and privacy.  https://github.com/w3c/chinese-ig-charter/issues/12 https://github.com/w3c/chinese-ig-charter/issues/13

More generally, I notice that this group's mailing list is pretty inactive (13 posts in the whole of 2020, all of them by Team), and I don't see much activity in the Github repo.  How active is the group, in general?

**Comment by xfq** [comment]
> More generally, I notice that this group's mailing list is pretty inactive (13 posts in the whole of 2020, all of them by Team), and I don't see much activity in the Github repo. How active is the group, in general?

Most activities of the group are [F2F meetings](https://www.w3.org/2018/chinese-web-ig/index.html#who). Organizing meetings takes a lot of time, which is one of the reasons why we created an IG instead of a CG (because IG needs FTE from the team). In addition to meetings, there are many informal discussions in private (among co-chairs) or semi-public channels (like in WeChat groups). We mentioned that in the charter:

> Informal coordination is done via the Interest Group's mailing lists as well as other communication channels by consent of the participants.

**Comment by samuelweiler** [comment]
charter to AC for review https://lists.w3.org/Archives/Public/public-new-work/2020Aug/0006.html

**Comment by xfq** [comment]
Rechartered: https://lists.w3.org/Archives/Public/public-chinese-web/2020Oct/0001.html
