### ISSUE TITLE
Open Screen protocol

### ISSUE THREAD

**Issue by tidoust** [w3c/strategy#49]
The [Second Screen CG](https://www.w3.org/community/webscreens/) started to discuss an [Open Screen Protocol](https://github.com/webscreens/openscreenprotocol/issues) for the Presentation API and the Remote Playback API developed by the Second Screen WG. This would improve the interoperability of implementations of these APIs.

**Comment by plehegar** [comment]
Isn't this addressed in the proposed charter?
[[
* suite of network protocols that allow user agents to implement the APIs in an interoperable fashion for browsers and presentation displays connected via the same local area network.
]]
See #194 

If yes, it would be better to close this issue since it has been "resolved".

**Comment by tidoust** [comment]
OK, closing the issue for now. The "resolved" status depends on the outcome of the rechartering in #194 but I guess we can always reopen the issue if the Open Screen Protocol remains out of scope of the Second Screen WG.
