### ISSUE TITLE
Blockchain

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#8]
https://www.w3.org/2016/04/blockchain-workshop/

**Comment by iherman** [comment]
@wseltzer with the existence of the blockchain CG, shouldn't this be part of incubation? Or would we move it there only when the CG clearly moves (if at all) towards an IG/WG?

**Comment by iherman** [comment]
Also... is the title "Workshop" appropriate? Do we plan another workshop?

**Comment by wseltzer** [comment]
@iherman good questions :) Yes, we should probably rename the overall issue to "Blockchain" and then catalog what's happened since the workshop

**Comment by wseltzer** [comment]
@JAlanBird offers to work with a technical expert, describing the business context and interested parties' use cases.

**Comment by iherman** [comment]
# Report of the first Linked Data and Distributed Ledgers Workshop

Workshop at WWW2017, Perth, AU, Apr. 4, 2017

See [program on line](https://sites.google.com/site/lddlworkshop2017/program). The presentation slides will become online soon.

This was the first of its kind. There was a general introductory keynote and also an overview of some of the current applications of various types of blockchains. The rest of the day, including a round table at the end, had presentations and discussed some issues, eg,:

- What can Linked Data technologies bring to blockchains or inspire blockchain evolution
	- better data modeling techniques on blockchain records and blocks, including ontologies for the description of state changes in blocks
	- blockchain, block, and record identities
	- linking blockchains among themselves, creating a graph of otherwise independent blockchains
	- HTTP Restful API-s for the management, creation, etc, of blocks and records (e.g., for blockchains that do not have the notion of miners)
- What can blockchain technologies bring to Linked Data or inspire in Linked Data evolution
	- importance of canonical graphs, and graph signatures
	- importance of time stamping of RDF graphs
	- use blockchains to represent provenance and identity of graphs 
	
All these are subject for further discussions. Some of these may become subject of subsequent W3C standardization work (the HTTP API came to the fore), some others may end up, for the time being, as member submission (canonicalization and signature of graphs). The thinking was to try to revitalize the Blockchain CG, which is not really active these days, and possibly trying to reorient it (the current CG is very much financial service oriented).

**Comment by msporny** [comment]
There are participants from these Blockchain companies actively participating in the joint meetings the W3C Credentials CG, W3C Digital Verification CG, and W3C Self-Sovereign Technology CG have been holding:

R3 (Banking Consortium Corda Blockchain)
Blockstream (Bitcoin Applications)
UPort (Ethereum Identity)
Evernym (Sovrin Blockchain)
Learning Machine (BlockCerts + Bitcoin)
BigChainDB (BigChain Blockchain)
Tierion (Blockchain Proof Anchoring)
Decentralized Identity Foundation (Microsoft Identity Blockchain)

to work on Decentralized Identifiers:

https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-fall2016/blob/master/final-documents/did-implementer-draft-10.pdf

That stuff dove-tails with the Verifiable Claims work... all of those Blockchain companies are at the table because they want to do Verifiable Claims in Blockchains and there seems to be community momentum to feed that work into a W3C WG (but it'll take 1-2 years to get there).

I raise this point because it may be that having a Blockchain CG may not be the best approach. Perhaps each area understanding how Blockchain may help them may be the best approach. This has certainly turned out to be the case in the Verifiable Claims work stream.

**Comment by iherman** [comment]
@msporny Is the idea to form a separate CG around this concept of DID? Or is a Workshop you are having in mind?

**Comment by msporny** [comment]
The Decentralized Identifier stuff is being incubated in the Credentials CG at present (which will change its name shortly to better match the new scope of work for the group). Workshops on the DID work have been progressing at Rebooting Web of Trust events held twice a year (the next one is in Boston, Oct 3rd-5th):

http://www.weboftrust.info/

So, W3C does not need to do anything about it other than:

1. Know that this Decentralized Identifier (DID) work is progressing in a W3C CG.
2. Know that the work is linked to the Verifiable Claims WG work.
3. Know that the work is heavily dependent on Blockchains and is a blockchain interoperability mechanism for creating and managing identifiers in a decentralized way.
4. Know that the CG desires to take it W3C standards track once it has been appropriately incubated (which may take another 12-24 months).

**Comment by svgeesus** [comment]
Closing as work completed, [DID WG formed](https://www.w3.org/groups/wg/did)
